language: php

os: linux

dist: bionic

php:
    - '7.4'
    - '7.3'

cache:
    directories:
        - ~/.composer/cache/files

services:
    - mysql

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - cp tests/Application/.env.test.dist tests/Application/.env.test
    - set -a && source tests/Application/.env.test && set +a

install:
    - composer update --no-interaction --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)

script:
    - composer validate --strict

    - composer analyse

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/phpunit
    - vendor/bin/doc-parser doc/Cookbook.md
