language: php

os: linux

dist: bionic

php:
    - '7.4'
    - '7.3'

jobs:
    include:
        -   env: SYLIUS_VERSION=1.7.*
        -   env: SYLIUS_VERSION=1.8.* ANALYSE=y

cache:
    directories:
        - ~/.composer/cache/files

services:
    - mysql

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - cp tests/Application/.env.test.dist tests/Application/.env.test
    - set -a && source tests/Application/.env.test && set +a

install:
    - composer require sylius/sylius:${SYLIUS_VERSION} --no-interaction --no-update

    - >-
        if [ "$SYLIUS_VERSION" = '1.7.*' ]; then
            cp etc/travis/sylius17/bundles.php tests/Application/config/
            cp etc/travis/sylius17/doctrine_migrations.yaml tests/Application/config/packages/
            cp etc/travis/sylius17/security.yaml tests/Application/config/packages/
        fi

    - composer update --no-interaction --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)

script:
    - composer validate --strict

    - >-
        if [ "$ANALYSE" = 'y' ]; then
            composer analyse
        fi

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/phpunit
    - vendor/bin/doc-parser doc/Cookbook.md
